swagger: "2.0"
info:
  title: Regent API
  description: API for managing regents
  version: 1.0.0
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /regent:
    get:
      summary: Get all regents
      responses:
        200:
          description: List of regents
          schema:
            type: array
            items:
              $ref: '#/definitions/Regent'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
  /regent/{id}:
    get:
      summary: Get a regent by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Regent details
          schema:
            $ref: '#/definitions/Regent'
        404:
          description: Regent not found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Regent:
    type: object
    properties:
      idregent:
        type: integer
        format: int64
      name:
        type: string
      capital:
        type: string
      area:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string